### ISSUE TITLE
way in filter

### ISSUE THREAD

**Issue by nicola-spb** [codesoap/pbf#1]
Hello,

Do you check ways (line across rectangle) without nodes in filter rectangle?

```
      \ (way)
       . (node)
_________________
|        \       |
|          \     |
-----------------
             \
               . (node)
                \ (way)
```

**Comment by codesoap** [comment]
No. Take a look at the documentation: https://pkg.go.dev/github.com/codesoap/pbf#Filter It says:
> Note that ways and relations which only pass through Location, but have no nodes there, will be missed.

**Comment by nicola-spb** [comment]
ok
